# Exercises

# Green 

# 1) Does the meta data frame contain all the relevant clinical parameters you can think of?

# Not to me. A future person who wanted to reuse these data might like to look for differences 
# between sex in community composition. But since subject sex is not identified in the meta 
# data, this won't be possible.

# 2) Which columns in meta are numeric?

# The easiest way to assess this would be just to look using str:

> str(meta)
'data.frame':	631 obs. of  16 variables:
  $ ecotype                          : chr  "missing" "missing" "missing" "missing" ...
$ broad.scale.environmental.context: chr  "missing" "missing" "missing" "missing" ...
$ latitude.and.longitude           : chr  "missing" "missing" "missing" "missing" ...
$ geographic.location              : chr  "USA: Ann Arbor" "USA: Ann Arbor" "USA: Ann Arbor" "USA: Ann Arbor" ...
$ host_clinical_state              : chr  "E" "B" "B" "B" ...
$ environmental.medium             : chr  "missing" "missing" "missing" "missing" ...
$ host                             : chr  "Homo sapiens" "Homo sapiens" "Homo sapiens" "Homo sapiens" ...
$ strain                           : chr  "missing" "missing" "missing" "missing" ...
$ isolation.and.growth.condition   : chr  "missing" "missing" "missing" "missing" ...
$ isolate                          : int  117 182 117 147 182 117 147 117 307 229 ...
$ collection.date                  : chr  "missing" "missing" "missing" "missing" ...
$ host.age                         : num  48.5 30.6 48.6 25.4 30.9 ...
$ host_disease_aggressiveness      : chr  "Mild" "Mild" "Mild" "Moderate/Severe" ...
$ local.environmental.context      : chr  "missing" "missing" "missing" "missing" ...
$ cultivar                         : chr  "missing" "missing" "missing" "missing" ...
$ host_fev1                        : int  44 83 51 46 79 51 44 51 100 48 ...

# A more advanced approach would be to use an apply function on the columns of meta like this

apply(meta,2,is.character)

# 3) What columns in meta are non-informative?

# I would say that any column that always has a blank value is non-informative.  

# 4) Add the 9th value to the Fibonacci sequence stored in x

# The 9th value is the 7th plus the 8th.

x[9] <- x[7] + x[8]

# 5) Make a boxplot of host fev1 as a function of host clinical state with 
# appropriate labels

boxplot(host_fev1 ~ host_clinical_state, data = InterestingMeta )

# 6) Save this plot to a pdf file using R, rather than the menu "Export --> Save as PDF...". 
# I did not tell you how to do this. Google knows. They often have great help pages.

pdf("FEV1vState.pdf")
boxplot(host_fev1 ~ host_clinical_state, data = InterestingMeta )
dev.off()

# Blue

# 1) Make a boxplot of fev1 as a function of host_disease_aggressiveness

boxplot(host_fev1 ~ host_disease_aggressiveness, data = InterestingMeta )

# The plot function can also use the formula interface that boxplot uses.

# 2) Use plot to make a scatter plot of fev1 vs age using this "~" based 
# syntax on the meta data frame.

plot(host_fev1 ~ host.age, data = InterestingMeta )

# 3) is there a trend in fev1 as a function of age in this data set?

# I can see a downward trend.

# The lm function also uses the formula syntax, and you can use it to
# fit a straight line to a set of x and y values. 

# Something like this

# fit <- lm(y ~ x, data=D)
# where x and y are columns in a data frame called D.

# 4) Use the lm function to fit a line to fev1 as a function of age in the
# meta data, saving the result in a variable called fit

fit <- lm(host_fev1 ~ host.age, data = InterestingMeta )


# The abline function in R understands linear model fits and 
# will place the regression line from a fit on top of a fit.

# abline(fit)

# 5) Use the plot and abline functions in succession to create a 
# scatter plot of fev1 as a function of age in the meta data frame
# and the regression line generated by lm.

plot(host_fev1 ~ host.age, data = InterestingMeta )
abline(fit)


# Black

# One can inspect the output of a linear model fit using the 
# summary function.

# 1) Is fev1 significantly correlated with age in this data set?

summary(fit)

# No. p = 0.121
